#!/bin/bash

if [ ! -e "setup.py" ]; then
	echo "The script must be executed from within the repository's root directory."
	exit
fi

docker run \
	--rm -it \
	--network=arouteserver --ip=192.0.2.99 \
	--name=ars_rc \
	-v `pwd`/example:/etc/exabgp \
	-v `pwd`/scripts/invalidroutesreporter.py:/etc/exabgp/invalidroutesreporter.py \
	pierky/exabgp:3.4.19 \
	env exabgp.log.destination=stdout exabgp.log.routes=false exabgp.daemon.user=root exabgp /etc/exabgp/exabgp.conf
